### ISSUE TITLE
FedEx Plugin Not Functioning for All Countries - SOAP API Issue

### ISSUE THREAD

**Issue by sanjay172** [nopSolutions/FedEx-plugin-for-nopcommerce#13]
I am experiencing issues with the FedEx plugin for NopCommerce. The plugin is not working for worldwide countries, and upon contacting FedEx customer care, I was informed that the plugin is currently using the SOAP API. They recommend switching to the REST API for proper functionality.

I have attached a screenshot of the conversation with FedEx customer care for your reference.

![image](https://github.com/user-attachments/assets/583541ec-400c-478c-b70f-f911db7ff887)

**Comment by AndreiMaz** [comment]
Already done - https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/commit/5a05827607dcf4839e834bc4cbf242bc3c2f084f

**Comment by sanjay172** [comment]
Hi, I have download and updated new plugin on my site but still it not working.

Pls help me.

![image](https://github.com/user-attachments/assets/8dc5f8ed-a1db-42af-8207-093afd9f2663)

**Comment by AndreiMaz** [comment]
@sanjay172 What version of nopCommerce are you using? What version of the plugin are you using?

**Comment by sanjay172** [comment]
Hi AndreiMaz,

First of all, thank you for responding so quickly.

FedEx - 1.36
![image](https://github.com/user-attachments/assets/527bf641-b115-4280-8de9-878ab5f0dc1f)

Nopcommerce - 
![image](https://github.com/user-attachments/assets/9cad8690-5e2d-41e9-a288-6d4b245f8ebc)

**Comment by AndreiMaz** [comment]
@sanjay172 We've upgrade our plugin to REST API only for nopCommerce 4.70. You can upgrade your nopCommerce store to 4.70 or dowgrade the plugin (apply the same changes manually) to 4.30

**Comment by sanjay172** [comment]
Okay, Thanks!!

**Comment by sanjay172** [comment]
Hi, Which specific code needs to be changed and in which files? Can you provide that information?

**Comment by AndreiMaz** [comment]
See  https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/commit/5a05827607dcf4839e834bc4cbf242bc3c2f084f

Please post on our forums for further support - https://www.nopcommerce.com/en/boards/

**Comment by mevinaykaushik2** [comment]
Posted to Forums as you said:
https://www.nopcommerce.com/en/boards/topic/101218/integration-of-latest-fedex-shipping-plugin-with-nopcommerce-430

**Comment by mevinaykaushik2** [comment]
@AndreiMaz , could you please guide me on the same . 
Unable to get it running in older version due to many conflicts. Is it possible that we can get a version of this plugin compatible with older nopCommerce, I am using 4.30.
