### ISSUE TITLE
FedEx Plugin Not Functioning for All Countries - SOAP API Issue (Already Replied by you but not working)

### ISSUE THREAD

**Issue by sanjay172** [nopSolutions/FedEx-plugin-for-nopcommerce#14]
I am experiencing issues with the FedEx plugin for NopCommerce. The plugin is not working for worldwide countries, and upon contacting FedEx customer care, I was informed that the plugin is currently using the SOAP API. They recommend switching to the REST API for proper functionality.

I have attached a screenshot of the conversation with FedEx customer care for your reference.

![image](https://github.com/user-attachments/assets/5dd7c8d2-53b4-4149-953f-27df82a7b1d8)

**You have replied to this issue before. I have updated the latest plugin, but it is still not working. Please help me.**

![image](https://github.com/user-attachments/assets/5341ef40-7997-4b8a-ac13-02b8ca7e7ee1)

**Comment by AndreiMaz** [comment]
Please do not duplicated issues. Post in the original one - https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/issues/13

**Comment by sanjay172** [comment]
Okay, Go it!
