### ISSUE TITLE
FedEx Ground Economy (SmartPost) Issues

### ISSUE THREAD

**Issue by ajcoll5** [nopSolutions/FedEx-plugin-for-nopcommerce#3]
While the plugin has an option in the admin configuration for FedEx SmartPost, it is not including the required fields in the requests to FedEx - therefore the response never contains SmartPost rates.

- The RequestedShipment node needs SmartPostDetail defined - namely the IndiciaSpecified and Indicia fields
-- IndiciaSpecified should be true
-- Indicia needs to have the SmartPost service type like Parcel Select, Media Mail (CD), or Bound Printed Matter. Parcel Select would probably be the most general option if not wanting to give the admin the ability to pick.
- "FXSP" needs to be added to the CarrierCodes.

Also, FedEx has rebranded SmartPost to [Ground Economy](https://www.fedex.com/en-us/shipping/ground/economy.html).

I'll follow up with a pull request shortly to address these.

**Comment by skoshelev** [comment]
Closed #3
