### ISSUE TITLE
Use the latest API version

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/FedEx-plugin-for-nopcommerce#5]
Let's use the latest API version. Currently we fetch FedEx rates Version 16. But there's Version 31 available.

The currently used version does not get the right prices anymore (Example INTERNATIONAL_PRIOIRTY  is no longer available with FedEx) and missing some other shipping options such as FedEx_INTERNATIONAL_PRIOIRTY  and FedEx_International Economy and so on.

Update the plugin for versions 4.60+

Forum source: https://www.nopcommerce.com/en/boards/topic/96893/fedex-plugin-nopcommerce-45

**Comment by rabihadada** [comment]
[FedEx_WebServices_RateServices_WSDLGuide_v2021.pdf](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/files/11448862/FedEx_WebServices_RateServices_WSDLGuide_v2021.pdf)

Hello Andrei,
Here it is. If you need any other information let me know and I will work on it. Thank you.

**Comment by atiq-bs23** [comment]
Hi @AndreiMaz 

I have taken the latest source code from your updated 4.5 branch. I have added 2 logs inside my code. You can check it from attached Screenshot.
![image](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/assets/113086917/cb0d60b7-4efb-4a79-8f15-d587cca21bc6)

Now we are getting a request log only because it is getting exception in line 21174

![image](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/assets/113086917/184d9d45-d365-44c1-b060-d2283d4d7fdc)


I am also giving you the xml+json body of the request. 


[FedX_Request_json.txt](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/files/11573556/FedX_Request_json.txt)
[FedX_request_xml.txt](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/files/11573557/FedX_request_xml.txt)


Please replace the values with yours
![image](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/assets/113086917/c75cee3b-b9de-40bd-bb16-b00eaa9ff6b5)

CC: @rabihadada

**Comment by skoshelev** [comment]
Hi @atiq-bs23. the Reference.cs file is automatically generated based on the definitions, it is better not to make changes to it, even such. 
Could you provide a stack of the exception you get when calling the FedexService.GetRatesAsync method?

**Comment by skoshelev** [comment]
@atiq-bs23. And another question, did you configure the plugin after installing the new version? Perhaps your old settings were removed when the plugin was replaced

**Comment by atiq-bs23** [comment]
I have configured it again so that it updates all settings value with proper key. 
![image](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/assets/113086917/68341aa1-51c9-45d4-8c0d-51babb0f55d1)

Then I have sent the same request. 
Here is the Stack Trace

```
at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location ---
   at FedexRate.RatePortTypeClient.getRatesAsync(RateRequest RateRequest) ************** Fault
```

@skoshelev

**Comment by skoshelev** [comment]
@atiq-bs23 How exactly do you call this method, can you provide the code?

**Comment by atiq-bs23** [comment]
@skoshelev I am trying to load shipping option from checkout (When it tries to load all options). It is exactly the same code from this updated repo.

**Comment by atiq-bs23** [comment]
I am also attaching the response from FedX

_Hi Rabih,

That is good news. I tried to load the query you shared, but I am unable to run it in SOAP as there is lots of elements with missing or wrong info.


Could you please try to load the following query instead ? or ask nopCommerce team to replicate the same?_  



[Sample XML Request with Specific Service - Going Life.txt](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/files/11574793/Sample.XML.Request.with.Specific.Service.-.Going.Life.txt)
[Sample XML Rate Request without Specific Service- Going Life.txt](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/files/11574794/Sample.XML.Rate.Request.without.Specific.Service-.Going.Life.txt)

@skoshelev

**Comment by rabihadada** [comment]
Hello Skoshelev,
Any updates or comments? Much appreciated

**Comment by skoshelev** [comment]
Hi @rabihadada. I analyzed the code and everything that you submitted for analysis, unfortunately at the moment I cannot determine what exactly is not working for you. There are no problems on the test environment (see screenshot)

![31-05-2023 094539](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/assets/16875599/5abe5639-6b23-4499-afca-7719c23ef43f)

You may have experienced some kind of failure when replacing a plugin or rebuilding the project. Please try uninstalling your plugin and removing it completely from the Nop.Web\Plugins directory. Then try to install the plugin from the [marketplace](https://www.nopcommerce.com/en/shipping-plugin-for-fedex)
