### ISSUE TITLE
Upgrade plugin from Web Services to FedEx APIs

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/FedEx-plugin-for-nopcommerce#6]
For nopCommerce version 4.60 and above, it is necessary to consider switching to a new FedEx API, since next year at least tracking orders using the old protocol will stop working. Below is a warning from the official website:

Caution: FedEx Web Services Tracking, Address Validation, and Validate Postal Codes WSDLS will be retired on May 15, 2024. The SOAP based FedEx Web Services is in development containment and has been replaced with FedEx RESTful APIs. To learn more and upgrade your integration from Web Services to FedEx APIs, please visit the [FedEx Developer Portal](https://developer.fedex.com/api/en-us/home.html).

**Comment by c4l3b** [comment]
Over the next couple days I am going to be working on updating the FedEx plugin to use their REST API for a customer. Would you consider a PR if the old web services were completely removed? This would be removing backwards compatibility for configuration, as the credentials are entirely different.

**Comment by AndreiMaz** [comment]
@c4l3b Sure, you're more than welcome to contribute

**Comment by nccerhostmaster** [comment]
May 15th is now just a few months away, and it's not looking promising for having REST API support available before then. 
 
When Fedex shuts down the Tracking, Address Validation, and Validate Postal Codes services, will this plugin continue to work for other services, i.e. rates? 

Will any other aspects of the current plugin continue to work after this?
Does anyone have a recommendation for an alternative?

**Comment by c4l3b** [comment]
@nccerhostmaster I do have a version that is using the REST API myself. I haven't had the opportunity to request a merge into the main repo - but I can try to do that soon

**Comment by nccerhostmaster** [comment]
@c4l3b Much appreciated, is your version feature equivalent?

**Comment by jrummell-elite** [comment]
I am in need of this as well for a client on 4.20. I was hoping I leverage the official 4.70 version and modify it as needed, but if I don't see anything in the next few weeks, we'll be attempting to implement this ourselves. Assuming the plugin hasn't changed too much between 4.20 and 4.70, I'll create a PR at that point.

**Comment by jrummell-elite** [comment]
Just to clarify the original comment - FedEx is not shutting down their current SOAP Web Services. So while it would be great to use the new REST APIs, the current plugin will continue working.

![image](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/assets/126172049/94d88a3b-3cd2-46a4-9106-be6c33a85c3a)

https://developer.fedex.com/api/en-us/support.html

**Comment by lakipolitis** [comment]
> @nccerhostmaster I do have a version that is using the REST API myself. I haven't had the opportunity to request a merge into the main repo - but I can try to do that soon

@c4l3b were you ever able to get that Pull Request in? I need to implement the same thing for a new FedEx customer and would also land up implementing shipping labels / voiding shipping labels. I'd prefer to start with something that already has some of that functionality than going about implementing this from scratch completely. I would obviously contribute everything that I develop as well.

**Comment by nccerhostmaster** [comment]
> Just to clarify the original comment - FedEx is not shutting down their current SOAP Web Services. So while it would be great to use the new REST APIs, the current plugin will continue working.

@jrummell-elite Have you gotten confirmation from Fedex on this? The quoted passage says the web services will continue to work for existing integrations, but what exactly does that mean? Are they still issuing credentials for the web services?

**Comment by jrummell-elite** [comment]
> > Just to clarify the original comment - FedEx is not shutting down their current SOAP Web Services. So while it would be great to use the new REST APIs, the current plugin will continue working.
> 
> @jrummell-elite Have you gotten confirmation from Fedex on this? The quoted passage says the web services will continue to work for existing integrations, but what exactly does that mean? Are they still issuing credentials for the web services?

That's a good question. My client has an existing integration, so I think they are fine. You may run into issues with new integrations.

**Comment by nccerhostmaster** [comment]
Fedex's announcement was vague, saying only that the web services were "placed into development containment." Since that phrase is meaningless to anyone outside of Fedex, I contacted Fedex developer support and was able to get the following information:
1. The Termination of Fedex Web Services was scheduled for May 15th, but has now been postponed until August of this year, which means we have more time than we thought
2. The tracking and validation functions will completely stop working at the end of August
3. The rating and shipping functions will continue to work for some time after that, but will eventually be phased out. No date has been specified for when this will happen yet
4. There has been no announced plan to disable signing up for web services or issuing credentials, so for now, setting up integrations should be possible. This will likely change in the future

My guess is we will be OK through the end of 2024 at least.

**Comment by skoshelev** [comment]
Closed #6
