### ISSUE TITLE
Error getting FedEx Rates

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/FedEx-plugin-for-nopcommerce#8]
Hello,

I am receiving this error 

There was no endpoint listening at https://ws.fedex.com/web-services/rate that could accept the message. This is often caused by an incorrect address or SOAP action. I'm running nop 4.6.4
![image](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/assets/12185742/78bfc8fd-e59d-4854-b4bb-6cf964a8cbaf)
![image](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/assets/12185742/6e695f95-2afc-41f4-bf1b-0a66aa8ec2f0)
and the FedEx 2.01 plugin
![image](https://github.com/nopSolutions/FedEx-plugin-for-nopcommerce/assets/12185742/3ee614fc-9c51-4e4d-b480-342dcfcbc445)
Any help would be appreciated!

Thank you,
Cameron

**Comment by skoshelev** [comment]
Hi @cklenk. I tested the plugin and found no problems. Check that the gateway you specified is available from your server. also try to use another address like this one https://gateway.fedex.com:443/web-services/rate

Closed #8

**Comment by cklenk** [comment]
> Hi @cklenk. I tested the plugin and found no problems. Check that the gateway you specified is available from your server. also try to use another address like this one https://gateway.fedex.com:443/web-services/rate


Okay will do I will look into that. Thank you for the tips!
